apiVersion: v1
kind: Service
metadata:
  name: flare-bank-service
  labels:
    app: flare-bank
spec:
  type: NodePort
  selector:
    app: flare-bank
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-metrics
      protocol: TCP
      port: 9117
      targetPort: 9117
