apiVersion: v1
kind: Service
metadata:
  name: flare-bank-service
spec:
  type: NodePort
  selector:
    app: flare-bank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
